apiVersion: apps/v1
kind: Deployment
# ...
---
apiVersion: v1
kind: Service
# ...
metadata:
  name: dotnet-app-deployment
spec:
  replicas: 3 # App ကို ၃ ခု ပွားပြီး run မည်
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-container
        image: mydockerapp/dotnet-app:v1 # သင်၏ docker image
        ports:
        - containerPort: 8080 # .NET 8 အတွက် standard port